<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Facade.NetworkManagement.Contracts\Facade.NetworkManagement.Contracts.csproj" />
    <ProjectReference Include="..\..\Network\Network.Client.Contracts\Network.Client.Contracts.csproj" />
    <ProjectReference Include="..\..\Network\Network.Contracts\Network.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
