<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Content\Content.Contracts\Content.Contracts.csproj" />
    <ProjectReference Include="..\..\Events\Events.Contracts\Events.Contracts.csproj" />
    <ProjectReference Include="..\..\Facade\Facade.Shared.Contracts\Facade.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\Identity.Contracts\Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Jobs\Jobs.Contracts\Jobs.Contracts.csproj" />
  </ItemGroup>

</Project>
