export const API_PATHS = {
  auth: {
    login: '/api/auth/login',
    register: '/api/auth/register',
    refresh: '/api/auth/refresh',
    logout: '/api/auth/logout',
    google: '/api/auth/google',
    facebook: '/api/auth/facebook',
    me: '/api/auth/me',
  },

  profile: {
    me: '/api/profile/me',
    search: '/api/profile/search',
    byUserId: (userId) => `/api/profile/${userId}`,
    recordView: (profileOwnerId) => `/api/profile/${profileOwnerId}/views`,
    avatar: '/api/profile/me/avatar',
    header: '/api/profile/me/header',
    profileViews: '/api/profile/me/profile-views',
    messageSettings: '/api/profile/me/message-settings',
  },

  professional: {
    base: '/api/professional',
    myExperiences: '/api/professional/me/experiences',
    experienceById: (experienceId) => `/api/professional/me/experiences/${experienceId}`,
    myEducations: '/api/professional/me/educations',
    educationById: (educationId) => `/api/professional/me/educations/${educationId}`,
    mySkills: '/api/professional/me/skills',
    userSkillById: (userSkillId) => `/api/professional/me/skills/${userSkillId}`,
    skillsCatalog: '/api/professional/skills',
    skillById: (skillId) => `/api/professional/skills/${skillId}`,
    myCertificates: '/api/professional/me/certificates',
    certificateById: (certificateId) => `/api/professional/me/certificates/${certificateId}`,
    certificateFile: (certificateId) => `/api/professional/me/certificates/${certificateId}/file`,
    myLanguages: '/api/professional/me/languages',
    userLanguageById: (userLanguageId) => `/api/professional/me/languages/${userLanguageId}`,
    languagesCatalog: '/api/professional/languages',
    languageById: (languageId) => `/api/professional/languages/${languageId}`,
    myCompanies: '/api/professional/me/companies',
    companyById: (companyId) => `/api/professional/companies/${companyId}`,
    userExperiences: (userId) => `/api/professional/users/${userId}/experiences`,
    userEducations: (userId) => `/api/professional/users/${userId}/educations`,
    userSkills: (userId) => `/api/professional/users/${userId}/skills`,
    userRecommendations: (userId) => `/api/professional/users/${userId}/recommendations`,
    recommendations: '/api/professional/recommendations',
  },

  content: {
    feed: '/api/content/feed',
    myPosts: '/api/content/me/posts',
    myPostById: (postId) => `/api/content/me/posts/${postId}`,
    userPosts: (userId) => `/api/content/users/${userId}/posts`,
    postById: (postId) => `/api/content/posts/${postId}`,
    mediaUpload: '/api/content/me/media/upload',
    postMedia: (postId) => `/api/content/me/posts/${postId}/media`,
    comments: (postId) => `/api/content/posts/${postId}/comments`,
    commentById: (commentId) => `/api/content/me/comments/${commentId}`,
    reactions: (postId) => `/api/content/posts/${postId}/reactions`,
    myReaction: (postId) => `/api/content/posts/${postId}/reactions/me`,
    views: (postId) => `/api/content/posts/${postId}/views`,
    myPostViews: (postId) => `/api/content/me/posts/${postId}/views`,
    savedPosts: '/api/content/me/saved-posts',
    savePost: (postId) => `/api/content/me/posts/${postId}/save`,
    hashtags: '/api/content/hashtags',
  },

  network: {
    contacts: '/api/network/me/contacts',
    incomingContacts: '/api/network/me/contacts/incoming',
    outgoingContacts: '/api/network/me/contacts/outgoing',
    pendingCounts: '/api/network/me/contacts/pending-counts',
    contactById: (contactId) => `/api/network/me/contacts/${contactId}`,
    acceptContact: (contactId) => `/api/network/me/contacts/${contactId}/accept`,
    rejectContact: (contactId) => `/api/network/me/contacts/${contactId}/reject`,
    cancelContact: (contactId) => `/api/network/me/contacts/${contactId}/cancel`,
    following: '/api/network/me/following',
    followingByUserId: (userId) => `/api/network/me/following/${userId}`,
    followers: '/api/network/me/followers',
    blockedUsers: '/api/network/me/blocked-users',
    blockedUserById: (userId) => `/api/network/me/blocked-users/${userId}`,
    groups: '/api/network/me/groups',
    myGroups: '/api/network/me/groups',
    groupById: (groupId) => `/api/network/me/groups/${groupId}`,
    groupMembers: (groupId) => `/api/network/me/groups/${groupId}/members`,
    groupPosts: (groupId) => `/api/network/me/groups/${groupId}/posts`,
    groupJoin: (groupId) => `/api/network/me/groups/${groupId}/join`,
    groupMembership: (groupId) => `/api/network/me/groups/${groupId}/membership`,
    groupAttachPost: (groupId, postId) => `/api/network/me/groups/${groupId}/posts/${postId}`,
    pages: '/api/network/me/pages',
    pageFollowing: '/api/network/me/pages/following',
    myPages: '/api/network/me/pages',
    pageById: (pageId) => `/api/network/me/pages/${pageId}`,
    pageFollow: (pageId) => `/api/network/me/pages/${pageId}/follow`,
    pageFollowers: (pageId) => `/api/network/me/pages/${pageId}/followers`,
  },

  messaging: {
    chats: '/api/messaging/me/chats',
    myChats: '/api/messaging/me/chats',
    chatById: (chatId) => `/api/messaging/me/chats/${chatId}`,
    chatMembers: (chatId) => `/api/messaging/me/chats/${chatId}/members`,
    chatJoin: (chatId) => `/api/messaging/me/chats/${chatId}/join`,
    chatLeave: (chatId) => `/api/messaging/me/chats/${chatId}/membership`,
    messages: (chatId) => `/api/messaging/me/chats/${chatId}/messages`,
    chatMessages: (chatId) => `/api/messaging/me/chats/${chatId}/messages`,
    messageById: (messageId) => `/api/messaging/me/messages/${messageId}`,
    readMessage: (messageId) => `/api/messaging/me/messages/${messageId}/read`,
    markMessageRead: (messageId) => `/api/messaging/me/messages/${messageId}/read`,
    messageMediaUpload: (messageId) => `/api/messaging/me/messages/${messageId}/media/upload`,
    messageMediaAttach: (messageId) => `/api/messaging/me/messages/${messageId}/media`,
  },

  jobs: {
    vacancies: '/api/jobs/vacancies',
    vacancyById: (vacancyId) => `/api/jobs/vacancies/${vacancyId}`,
    myVacancies: '/api/jobs/me/vacancies',
    myVacancyById: (vacancyId) => `/api/jobs/me/vacancies/${vacancyId}`,
    apply: (vacancyId) => `/api/jobs/me/vacancies/${vacancyId}/apply`,
    favorites: '/api/jobs/me/favorites',
    favoriteByVacancyId: (vacancyId) => `/api/jobs/me/favorites/${vacancyId}`,
    applications: '/api/jobs/me/applications',
    myApplications: '/api/jobs/me/applications',
    recommendedQueries: '/api/jobs/recommended-queries',
  },

  events: {
    discover: '/api/events',
    list: '/api/events',
    byId: (eventId) => `/api/events/${eventId}`,
    eventById: (eventId) => `/api/events/${eventId}`,
    myEvents: '/api/events/me',
    attending: '/api/events/me/attending',
    join: (eventId) => `/api/events/me/${eventId}/join`,
    attendance: (eventId) => `/api/events/me/${eventId}/attendance`,
    leave: (eventId) => `/api/events/me/${eventId}/attendance`,
    speakers: (eventId) => `/api/events/${eventId}/speakers`,
    speakersCatalog: '/api/events/speakers',
    schedule: (eventId) => `/api/events/${eventId}/schedule`,
    cover: (eventId) => `/api/events/me/${eventId}/cover`,
    attendees: (eventId) => `/api/events/${eventId}/attendees`,
  },

  notifications: {
    mine: '/api/notifications/me',
    me: '/api/notifications/me',
    byId: (notificationId) => `/api/notifications/me/${notificationId}`,
    markRead: (notificationId) => `/api/notifications/me/${notificationId}/read`,
    readAll: '/api/notifications/me/read-all',
    markAllRead: '/api/notifications/me/read-all',
    activity: '/api/notifications/me/activity',
  },

  admin: {
    stats: {
      overview: '/api/admin/stats/overview',
    },
    users: {
      list: '/api/admin/users',
      byId: (userId) => `/api/admin/users/${userId}`,
      lock: (userId) => `/api/admin/users/${userId}/lock`,
      unlock: (userId) => `/api/admin/users/${userId}/unlock`,
      restore: (userId) => `/api/admin/users/${userId}/restore`,
      roles: (userId) => `/api/admin/users/${userId}/roles`,
      roleByName: (userId, roleName) => `/api/admin/users/${userId}/roles/${encodeURIComponent(roleName)}`,
    },
    roles: {
      list: '/api/admin/roles',
    },
    content: {
      posts: '/api/admin/content/posts',
      postById: (postId) => `/api/admin/content/posts/${postId}`,
      restorePost: (postId) => `/api/admin/content/posts/${postId}/restore`,
      comments: '/api/admin/content/comments',
      commentById: (commentId) => `/api/admin/content/comments/${commentId}`,
      restoreComment: (commentId) => `/api/admin/content/comments/${commentId}/restore`,
    },
    jobs: {
      vacancies: '/api/admin/jobs/vacancies',
      vacancyById: (vacancyId) => `/api/admin/jobs/vacancies/${vacancyId}`,
      restoreVacancy: (vacancyId) => `/api/admin/jobs/vacancies/${vacancyId}/restore`,
    },
    events: {
      list: '/api/admin/events',
      byId: (eventId) => `/api/admin/events/${eventId}`,
      restore: (eventId) => `/api/admin/events/${eventId}/restore`,
    },
    statsOverview: '/api/admin/stats/overview',
    rolesList: '/api/admin/roles',
    usersList: '/api/admin/users',
    userById: (userId) => `/api/admin/users/${userId}`,
    contentPosts: '/api/admin/content/posts',
    contentComments: '/api/admin/content/comments',
    jobsVacancies: '/api/admin/jobs/vacancies',
    eventsList: '/api/admin/events',
  },

  ai: {
    recommendedJobs: '/api/ai/recommended-jobs',
    careerAdvice: '/api/ai/career-advice',
  },
};

export default API_PATHS;
