<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Jobs.Contracts\Jobs.Contracts.csproj" />
    <ProjectReference Include="..\Jobs.DataAccess\Jobs.DataAccess.csproj" />
    <ProjectReference Include="..\Jobs.Events.Contracts\Jobs.Events.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\Identity.Events.Contracts\Identity.Events.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
