<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Facade.JobsManagement.Contracts\Facade.JobsManagement.Contracts.csproj" />
    <ProjectReference Include="..\..\Facade\Facade.Shared.Contracts\Facade.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\Jobs\Jobs.Client.Contracts\Jobs.Client.Contracts.csproj" />
    <ProjectReference Include="..\..\Jobs\Jobs.Contracts\Jobs.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
