<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Facade\Facade.Shared.Contracts\Facade.Shared.Contracts.csproj" />
    <ProjectReference Include="..\Facade.AdminManagement.Contracts\Facade.AdminManagement.Contracts.csproj" />
    <ProjectReference Include="..\..\Content\Content.Client.Contracts\Content.Client.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\Identity.Client.Contracts\Identity.Client.Contracts.csproj" />
    <ProjectReference Include="..\..\Jobs\Jobs.Client.Contracts\Jobs.Client.Contracts.csproj" />
  </ItemGroup>

</Project>
