<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Facade.ContentManagement.Contracts\Facade.ContentManagement.Contracts.csproj" />
    <ProjectReference Include="..\..\Content\Content.Client.Contracts\Content.Client.Contracts.csproj" />
    <ProjectReference Include="..\..\Content\Content.Contracts\Content.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
