<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Content.Contracts\Content.Contracts.csproj" />
    <ProjectReference Include="..\Content.Services\Content.Services.csproj" />
    <ProjectReference Include="..\Content.DataAccess\Content.DataAccess.csproj" />
    <ProjectReference Include="..\Content.Client\Content.Client.csproj" />
    <ProjectReference Include="..\Content.Client.Contracts\Content.Client.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.6" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
