export const initialNetworkPeople = [
  {
    id: "n1",
    name: "David Jonson",
    role: "Lead UI/UX Designer",
    handle: "JonsonCPDR",
    seed: "DavidJonson",
    keywords: "design ui ux figma product",
    mutual: 14,
  },
  {
    id: "n2",
    name: "Duncan Callahan",
    role: "Senior UX Researcher",
    handle: "DuncanUX",
    seed: "DuncanCallahan",
    keywords: "ux research usability testing",
    mutual: 9,
  },
  {
    id: "n3",
    name: "Sarah Chen",
    role: "Product Designer · Figma",
    handle: "SarahChen",
    seed: "SarahChen",
    keywords: "design figma product ui",
    mutual: 17,
  },
  {
    id: "n4",
    name: "Maria Rodriguez",
    role: "Senior UX Researcher",
    handle: "MariaRdz",
    seed: "MariaRodriguez",
    keywords: "ux research analytics",
    mutual: 6,
  },
  {
    id: "n5",
    name: "James Lee",
    role: "UI Engineer",
    handle: "JamesLeeDev",
    seed: "JamesLee",
    keywords: "frontend react css engineer",
    mutual: 11,
  },
  {
    id: "n6",
    name: "Joshua Cortez",
    role: "UI/UX Designer",
    handle: "JoshCortez",
    seed: "JoshuaCortez",
    keywords: "design ui ux web",
    mutual: 7,
  },
  {
    id: "n7",
    name: "Marcus Dias",
    role: "Senior Design Manager · Microsoft",
    handle: "MarcusDias",
    seed: "MarcusDias",
    keywords: "design manager leadership microsoft",
    mutual: 20,
  },
  {
    id: "n8",
    name: "Alena Curtis",
    role: "Product Designer",
    handle: "AlenaCurtis",
    seed: "Alena",
    keywords: "product design ui prototyping",
    mutual: 8,
  },
  {
    id: "n9",
    name: "Elena Volkov",
    role: "Frontend Developer · Stripe",
    handle: "ElenaVolkov",
    seed: "ElenaVolkov",
    keywords: "frontend react typescript javascript",
    mutual: 16,
  },
  {
    id: "n10",
    name: "Andrii Rotar",
    role: "Full Stack Engineer",
    handle: "AndriiRotar",
    seed: "AndriiRotar",
    keywords: "fullstack react node engineer",
    mutual: 10,
  },
  {
    id: "n11",
    name: "Timur Yamchuk",
    role: "Backend Developer",
    handle: "TimurYamchuk",
    seed: "TimurYamchuk",
    avatar: "/auth/assets/timur-yamchuk-avatar.png",
    keywords: "backend java spring api",
    mutual: 12,
  },
  {
    id: "n12",
    name: "Priya Patel",
    role: "DevOps Engineer · Datadog",
    handle: "PriyaDevOps",
    seed: "PriyaPatel",
    keywords: "devops kubernetes aws sre",
    mutual: 13,
  },
  {
    id: "n13",
    name: "Alex Kim",
    role: "React Developer",
    handle: "AlexKimDev",
    seed: "AlexKim",
    keywords: "react javascript frontend",
    mutual: 5,
  },
  {
    id: "n14",
    name: "Nina Petrova",
    role: "UX Research Lead",
    handle: "NinaPetrova",
    seed: "NinaPetrova",
    keywords: "ux research interviews usability",
    mutual: 15,
  },
  {
    id: "n15",
    name: "Ryan O'Brien",
    role: "Product Manager · Atlassian",
    handle: "RyanOBrien",
    seed: "RyanOBrien",
    keywords: "product manager agile roadmap",
    mutual: 9,
  },
  {
    id: "n16",
    name: "Sophie Martin",
    role: "Visual UI Designer",
    handle: "SophieMartin",
    seed: "SophieMartin",
    keywords: "ui visual design branding",
    mutual: 8,
  },
  {
    id: "n17",
    name: "Liam Nguyen",
    role: "Data Analyst · Airtable",
    handle: "LiamNguyen",
    seed: "LiamNguyen",
    keywords: "data analyst sql bi metrics",
    mutual: 7,
  },
  {
    id: "n18",
    name: "Abram Lipshutz",
    role: "Design Systems Engineer",
    handle: "AbramLipshutz",
    seed: "Abram",
    keywords: "design systems frontend css tokens",
    mutual: 12,
  },
];

export const initialVacancies = [
  { id: "v1", title: "React Frontend Engineer", company: "TechNova", city: "Warsaw" },
  { id: "v2", title: "UI Engineer", company: "Globex", city: "Berlin" },
  { id: "v3", title: "Product Frontend Dev", company: "Innova", city: "Kyiv" },
];

export const initialChats = [
  {
    id: "c1",
    peer: "Marcus Rene",
    online: true,
    messages: [
      { id: "m1", fromMe: false, text: "Hi! Ready for tomorrow's demo?" },
      { id: "m2", fromMe: true, text: "Yes, finishing the chat flow now." },
    ],
  },
  {
    id: "c2",
    peer: "Alena Orlova",
    online: false,
    messages: [{ id: "m3", fromMe: false, text: "Can you review new profile cards?" }],
  },
];
