<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Content.Contracts\Content.Contracts.csproj" />
    <ProjectReference Include="..\Content.DataAccess\Content.DataAccess.csproj" />
    <ProjectReference Include="..\Content.Events.Contracts\Content.Events.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\Identity.Events.Contracts\Identity.Events.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
