<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.26" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.414.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Identity\Identity.Services\Identity.Services.csproj" />
    <ProjectReference Include="..\..\Identity\Identity.Contracts\Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\Identity.DataAccess\Identity.DataAccess.csproj" />
    <ProjectReference Include="..\..\Identity\Identity.Events.Contracts\Identity.Events.Contracts.csproj" />
    <ProjectReference Include="..\..\Content\Content.Services\Content.Services.csproj" />
    <ProjectReference Include="..\..\Content\Content.Contracts\Content.Contracts.csproj" />
    <ProjectReference Include="..\..\Content\Content.DataAccess\Content.DataAccess.csproj" />
    <ProjectReference Include="..\..\Profile\Profile.Services\Profile.Services.csproj" />
    <ProjectReference Include="..\..\Profile\Profile.Contracts\Profile.Contracts.csproj" />
    <ProjectReference Include="..\..\Profile\Profile.DataAccess\Profile.DataAccess.csproj" />
    <ProjectReference Include="..\..\Network\Network.Services\Network.Services.csproj" />
    <ProjectReference Include="..\..\Network\Network.Contracts\Network.Contracts.csproj" />
    <ProjectReference Include="..\..\Network\Network.DataAccess\Network.DataAccess.csproj" />
    <ProjectReference Include="..\..\Professional\Professional.Services\Professional.Services.csproj" />
    <ProjectReference Include="..\..\Professional\Professional.Contracts\Professional.Contracts.csproj" />
    <ProjectReference Include="..\..\Professional\Professional.DataAccess\Professional.DataAccess.csproj" />
    <ProjectReference Include="..\..\FileStorage\Facade.FileStorage.Services\Facade.FileStorage.Services.csproj" />
    <ProjectReference Include="..\..\FileStorage\Facade.FileStorage.Contracts\Facade.FileStorage.Contracts.csproj" />
  </ItemGroup>

</Project>
